Values:
  Join-Enabled: true # If join messages should be enabled - Must be a boolean value
  Leave-Enabled: true # If leave messages should be enabled - Must be a boolean value
  First-Join-Enabled: true # If first join messages should be enabled - Must be a boolean value
