Values:
  Join-Enabled: true # If join messages should be enabled - Must be a boolean value
  Join-Image-URL: example.join.message.com/image_join.png # Image that the join message will use - Must be a string value without double-quotes

  Leave-Enabled: true # If leave messages should be enabled - Must be a boolean value
  Leave-Image-URL: example.leave.message.com/image_leave.png # Image that the leave message will use - Must be a string value without double-quotes
  
  First-Join-Enabled: true # If first join messages should be enabled - Must be a boolean value
  First-Join-Image-URL: example.first-join.message.com/image_first-join.png # Image that the first join message will use - Must be a string value without double-quotes
